# Generated by Django 3.2.25 on 2024-08-10 12:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_tickets', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('available_tickets', models.PositiveIntegerField()),
                ('winners_drawn', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='raffles.raffle')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.PositiveIntegerField()),
                ('verification_code', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('isWinner', models.BooleanField(default=False)),
                ('prize', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', related_query_name='ticket', to='raffles.raffle')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('raffle', 'ip_address')},
            },
        ),
    ]
