# Generated by Django 3.2.25 on 2024-08-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='total_tickets',
            field=models.PositiveIntegerField(),
        ),
    ]
