# Generated by Django 3.2.25 on 2024-08-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0002_auto_20240810_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='available_tickets',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='total_tickets',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.IntegerField(),
        ),
    ]
