# Generated by Django 3.2.25 on 2024-08-10 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0003_auto_20240810_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
