# Generated by Django 3.2.25 on 2024-08-11 15:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0004_alter_raffle_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='isWinner',
            new_name='has_won',
        ),
        migrations.AlterField(
            model_name='prize',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='raffles.raffle'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
