# Generated by Django 3.2.25 on 2024-08-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0005_auto_20240811_1527'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('raffle', 'ticket_number'), ('raffle', 'ip_address')},
        ),
    ]
