# Generated by Django 3.2.25 on 2024-08-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0006_alter_ticket_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='verification_code',
            field=models.CharField(editable=False, max_length=128),
        ),
    ]
