# Generated by Django 3.2.25 on 2024-08-12 02:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0012_alter_ticket_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
